
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsdczmotzucavdbnohfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZGN6bW90enVjYXZkYm5vaGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjI4NzQsImV4cCI6MjA2MTIzODg3NH0.PUVButf3Fs78PW5gQ8gyjFpshieqJLt-U864T_2Hm1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Initialize services - completely removed automatic data loading
export const initializeSupabaseData = async () => {
  try {
    // Only check auth status, don't load any data
    const { data: { session } } = await supabase.auth.getSession();
    
    if (!session) {
      console.log("No authenticated session");
    } else {
      console.log("User authenticated");
    }
  } catch (error) {
    console.error("Error checking authentication:", error);
  }
};
