
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsdczmotzucavdbnohfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZGN6bW90enVjYXZkYm5vaGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjI4NzQsImV4cCI6MjA2MTIzODg3NH0.PUVButf3Fs78PW5gQ8gyjFpshieqJLt-U864T_2Hm1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    storage: localStorage
  }
});

// Initialize services - completely skip authentication checks
export const initializeSupabaseData = async () => {
  console.log("Skipping authentication checks - data will be loaded without authentication");
  // No authentication checks, no data loading
};
