

// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsdczmotzucavdbnohfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzZGN6bW90enVjYXZkYm5vaGZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NjI4NzQsImV4cCI6MjA2MTIzODg3NH0.PUVButf3Fs78PW5gQ8gyjFpshieqJLt-U864T_2Hm1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: localStorage
  }
});

// Initialize services
import { initializeLocalStorage } from '@/services/mockData';
import { getInvoices } from '@/services/invoices';

// Call this function to ensure mock data is loaded
export const initializeSupabaseData = async () => {
  // Check if user is authenticated
  const { data: { session } } = await supabase.auth.getSession();
  
  if (!session) {
    // If no authenticated session, fallback to local storage
    initializeLocalStorage();
    getInvoices(); // Initialize invoice data
  } else {
    console.log("User authenticated, using Supabase data");
  }
};
